name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup vcpkg
        run: |
          cd ${{github.workspace}}
          git clone https://github.com/Microsoft/vcpkg.git
          ls
          cd vcpkg
          git checkout 0fe8c9dece39cf79ba0671c97a9de9db3a193589
          ./bootstrap-vcpkg.sh
          echo "${{github.workspace}}/vcpkg" >> "$GITHUB_PATH"

      - name: Install dependencies
        run: vcpkg install

      - name: Create Release Package
        if: matrix.os == 'windows-latest'
        run: |
          $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
          Compress-Archive -Path ${{github.workspace}}/vcpkg_installed -DestinationPath vcpkg_installed_${{ matrix.os }}.zip

      - name: Create Release Package (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          version=${GITHUB_REF#refs/tags/v}
          zip -r vcpkg_installed_${{ matrix.os }}.zip vcpkg_installed/

      - name: Create Release Package (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          version=${GITHUB_REF#refs/tags/v}
          zip -r vcpkg_installed_${{ matrix.os }}.zip vcpkg_installed/

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: vcpkg_installed_${{ matrix.os }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
