name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git -b 566f9496b7e00ee0cc00aca0ab90493d122d148a
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install dependencies
        run: ./${{github.workspace}}/vcpkg/vcpkg install

      - name: Create Release Package
        if: matrix.os == 'windows-latest'
        run: |
          $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
          Compress-Archive -Path ${{github.workspace}}/vcpkg_installed -DestinationPath vcpkg_installed_windows.zip

      - name: Create Release Package (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          version=${GITHUB_REF#refs/tags/v}
          zip -r vcpkg_installed_linux.zip vcpkg_installed/

      - name: Create Release Package (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          version=${GITHUB_REF#refs/tags/v}
          zip -r vcpkg_installed_macos.zip vcpkg_installed/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vcpkg_installed_${{ matrix.os }}
          path: vcpkg_installed_*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/vcpkg_installed_windows-latest/vcpkg_installed_windows.zip
            artifacts/vcpkg_installed_ubuntu-latest/vcpkg_installed_linux.zip
            artifacts/vcpkg_installed_macos-latest/vcpkg_installed_macos.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
