name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '566f9496b7e00ee0cc00aca0ab90493d122d148a'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Create Release Package
        run: |
          $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
          Compress-Archive -Path ${{github.workspace}}/vcpkg_installed -DestinationPath vcpkg_installed.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: vcpkg_installed.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
