name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Setup vcpkg
        run: |
          cd ${{github.workspace}}
          git clone https://github.com/Microsoft/vcpkg.git
          ls
          cd vcpkg
          git checkout 0fe8c9dece39cf79ba0671c97a9de9db3a193589
          ./bootstrap-vcpkg.sh
          echo "${{github.workspace}}/vcpkg" >> "$GITHUB_PATH"
  
      - name: Install dependencies
        run: vcpkg install