name: Build with Vcpkg

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: '**/vcpkg.json'
        vcpkgConfigurationJsonGlob: '**/vcpkg-configuration.json'
        runVcpkgInstall: true
        doNotCache: false
 