name: Build with Vcpkg

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache vcpkg installed
      id: vcpkg-installed
      uses: actions/cache@v3
      with:
          path: vcpkg_installed
          key: vcpkg_installed

    - name: Setup Vcpkg
      if: steps.vcpkg-installed.outputs.cache-hit != 'true'
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: '**/vcpkg.json'
        vcpkgConfigurationJsonGlob: '**/vcpkg-configuration.json'
        runVcpkgInstall: true
        doNotCache: false
 