name: ROS2 Jazzy CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - jazzy
        include:
          - docker_image: ubuntu:noble
            ros_distribution: jazzy
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: src/my_package

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
            python3-pip \
            python3-pytest \
            python3-colcon-common-extensions \
            python3-colcon-mixin \
            python3-rosdep \
            python3-vcstool \
            python3-rosinstall-generator \
            build-essential \
            cmake \
            git

      - name: Initialize rosdep
        run: |
          rosdep init
          rosdep update
